[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
extend-select = [
  # pydocstyle
  "D",
]
ignore = ["F401", "UP009", "D415"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
pretty = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.coverage.report]
exclude_lines = [
  "if 0:",
  "if __name__ == .__main__.:",
]

[tool.pytest.ini_options]
addopts = "-ra --timeout=10 --reruns 2 --reruns-delay 1"
