name: Builds

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Out
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Inclusiveness Analyze
        uses: microsoft/InclusivenessAnalyzer@v1.0.1
        continue-on-error: true

      - name: Prettify markdown
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{yml,md}
          commit_message: "Automatically Prettified Markdown"
          dry: True
        continue-on-error: true

  build:
    runs-on: ubuntu-latest

    needs: prettify

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checking Out
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ -f requirements.txt ]]; then python -m pip install -r requirements.txt; fi
          if [[ -f requirements-dev.txt ]]; then python -m pip install -r requirements-dev.txt; fi

      - name: Generate sub-tables & Build
        run: make

      - name: Lint & Format
        run: make lint

      - name: pre-commit
        run: make pre-commit

      - name: publish site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Awesome-IntelligentCarRace-Site
          path: site/

      - name: Coverage test
        run: make unit-tests

      - name: Upload coverage reports to Codecov
        if: github.repository == 'ittuann/Awesome-IntelligentCarRace' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: Upload coverage reporter to Codacy
        if: github.repository == 'ittuann/Awesome-IntelligentCarRace' && github.ref == 'refs/heads/main'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
        continue-on-error: true
